baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
defaultContentLanguage = "fr"
title = "Le Fil d'Ariane | Yoga"
theme = "hugo-theme-massively"
[Params]
  prod_deploy_url = "https://ariane.yoga"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[menu]
  [[menu.main]]
    name = "Ateliers"
    url = "/"
    weight = 3
  [[menu.main]]
    name = "Pratiques"
    url = "/pratiques/"
    weight = 5
  [[menu.main]]
    name = "Cours"
    url = "/cours/"
    weight = 7
  [[menu.main]]
    name = "Ariane"
    url = "/a-propos/"
    weight = 9

[languages]
# [languages.en]
#   languageName = "English"
[languages.fr]
  languageName = "Français"
